name: agriteck_user
description: A new Flutter application.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  fluttertoast: ^8.0.9
  floating_action_bubble: ^1.1.4
  # flutter_tflite: ^1.0.1
  tflite: any
  intl: ^0.17.0
  async_loader: ^0.1.2
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  pinput: ^2.2.12
  shared_preferences: ^2.0.15
  firebase_storage: ^10.3.7
  cloud_firestore: ^3.4.6
  steel_crypt: ^3.0.0+1
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  cached_network_image: ^3.2.1
  get: ^4.6.5
  dio: ^4.0.6
  syncfusion_flutter_charts: ^20.2.45
  intl_phone_field: ^3.1.0
  flutter_native_splash: ^2.2.9
  modal_bottom_sheet: ^2.1.2
  timeago: ^3.3.0
  flutter_smart_dialog: ^4.5.5+6
  after_layout: ^1.1.1
  persistent_bottom_nav_bar_v2: ^4.2.5
  

  
dependency_overrides:
  image_picker_android: 0.8.4+13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/back.png"
  android: true
  ios: true


  #flutter pub run flutter_native_splash:create
flutter:
  uses-material-design: true

  assets:
    - assets/diseases/
    - assets/icons/
    - assets/images/
    - assets/plants/
    - assets/
    - assets/mobilenet_model/

